export const GET_TODO_LIST = 'GET_TODO_LIST';
export const SET_TODO_ITEM = 'SET_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const SORT_TODO_LIST_BY_TITLE = 'SORT_TODO_LIST_BY_TITLE';
export const SORT_TODO_LIST_BY_DATE = 'SORT_TODO_LIST_BY_DATE'
